---
title: "Summary Visualizations for EconDec-OA"
output: html_notebook
---

When you save the notebook, an HTML file containing the code and output will be saved alongside it (click the *Preview* button or press *Ctrl+Shift+K* to preview the HTML file).

Requires `tidyverse` and `ggpubr` packages to be installed:
```
install.packages('tidyverse')
install.packages('ggpubr')
```


#### Set Parameters
```{r}
library(tidyverse)

# Color Palettes for Bar Plot
bar_color_palette <- 'startrek'
bar_fill_palette <- 'futurama'

# Color Palette for Asymmetry Curves
line_color_palette <- c('cornflowerblue','indianred2')
```


#### Read & Factorize Trial-Level Data
```{r}
data <- read.csv('../derivatives/main_trial_level.csv')

data$AgeGroup <- factor(data$AgeGroup)
data$SubjNum <- factor(data$SubjNum)
data$StockValue <- factor(data$StockValue)
```


#### Group & Summarize
```{r}
grp_level <- data %>%
	group_by(AgeGroup,StockValue) %>%
	summarize(
	  MeanError = mean(val_estdiff_valid, na.rm = TRUE),
	  StdErr = sd(val_estdiff_valid, na.rm = TRUE) / sqrt(length(val_estdiff_valid))
	  )
spread(select(grp_level,StockValue,MeanError),StockValue,MeanError)
```



```{r}
# Bar Plot Domain-Magnitude Interaction Between Groups
ggplot(grp_level, aes(x = AgeGroup, y = MeanError)) + 
	geom_bar(
		aes(color = StockValue, fill = StockValue),
		stat = 'identity', position = position_dodge()
		) +
	ggpubr::color_palette(bar_color_palette) + 
	ggpubr::fill_palette(bar_fill_palette) + 
	ggpubr::theme_pubclean()
```



```{r}
# Line Plot Young Adults' Domain Asymmetry Curves
ya_error_level <- filter(data, AgeGroup == 1)  %>%
  group_by(Domain, ObjectiveProb = TrueProbGood) %>%
  summarize(
    SubjectiveProb = mean(ProbGood, na.rm = TRUE),
    ErrUpper = SubjectiveProb + 2 *(sd(ProbGood, na.rm = TRUE) / sqrt(length(ProbGood))),
    ErrLower = SubjectiveProb - 2 *(sd(ProbGood, na.rm = TRUE) / sqrt(length(ProbGood)))
    )
ggplot(ya_error_level, aes(x=ObjectiveProb, y=SubjectiveProb, color=Domain)) +
  geom_smooth() +
  #geom_ribbon(aes(ymin=ErrLower, ymax=ErrUpper), fill='lightgrey',linetype=0) +
  #geom_line() +
  coord_cartesian(xlim=c(0,1),ylim=c(0,1)) +
  geom_abline(aes(slope=1,intercept=0),linetype=2) +
  xlab('Objective Probability') + ylab('Estimation') +
  ggtitle('Young Adults\' Error Asymmetry') +
  ggpubr::color_palette(line_color_palette) +
  theme_minimal(base_size = 12)
```



```{r}
# Line Plot Older Adults' Domain Asymmetry Curves
oa_error_level <- filter(data, AgeGroup == 2)  %>%
  group_by(Domain, ObjectiveProb = TrueProbGood) %>%
  summarize(
    SubjectiveProb = mean(ProbGood, na.rm = TRUE),
    ErrUpper = SubjectiveProb + 2 *(sd(ProbGood, na.rm = TRUE) / sqrt(length(ProbGood))),
    ErrLower = SubjectiveProb - 2 *(sd(ProbGood, na.rm = TRUE) / sqrt(length(ProbGood)))
    )
ggplot(oa_error_level, aes(x=ObjectiveProb, y=SubjectiveProb, color=Domain)) +
  geom_smooth() + coord_cartesian(xlim=c(0,1),ylim=c(0,1)) +
  #geom_ribbon(aes(ymin=ErrLower, ymax=ErrUpper), fill='lightgrey', linetype=0) +
  #geom_line() + 
  geom_abline(aes(slope=1,intercept=0),linetype=2) +
  ggtitle('Older Adults\' Error Asymmetry') +
  xlab('Objective Probability') + ylab('Estimation') +
  ggpubr::color_palette(line_color_palette) +
  theme_minimal(base_size = 12)
```

